language: bash
services: docker
matrix:
  include:
  - os: linux
    env: VERSION=1.13 VARIANT=buster
  - os: linux
    env: VERSION=1.12 VARIANT=buster
before_script:
- echo "this is before_script"
- env | sort
script:
- |
  (
    set -Eeuo pipefail
    set -x
    echo "this is script"
    docker build -t infmaze/base-image .
    #docker build -t "$image" .
  )
after_script:
- docker images
- echo "$DOCKER_PASSWORD" | docker login -u "infmaze" --password-stdin
- docker push infmaze/base-image
after_success:
- echo "after_success"
env:
  global:
  - secure: d+6psc8xXaoV4m3shZ3jM3PGNfO6nb2cNgNJIq3Y/DDcJNnwe9Vlh3YOJDxDfpE9ADNeT5M5h4QtdyvsHJKcP0kSSWL8IqF192SzNqKWUJKl+8+1kIPJYNWfpUUixxSrHgWBacq1Q7ko8jrzMIDDJ2SMR3AOFMayWP+QS62Wue+0d5CxBOVfCOQswk0sKERdVvfIn0v1zXSxIP2heq+TmLBbQop3EUfXlCYMbIzxdy69oOfUIrHcRPFSdrrCwOtEsd9Eg5n6v/y7oGPd76VL7Jhn6TWFeV/gyUMMiR60tIH3rHqFTAX/8wXtfQfZItg3AsvpcDD/d0VWAu/LsxBCqHc9OpPpfNzQdgUke2FEayl/vcpqlN7raTJ97jgUhYcX5hbfGco7sCUvNgYQ2zbMbJgFUxYt8EUtfsKI2PHhxRTpwGzwKeKUxIspIWN1odrrfHLJpvAFByyjXDGBKIUYg3od6NmHcmwLctrzk3bRpda42er/QkxOOFVNU3BHeGD9E6YThK3kgOowUm5dBuB0zVVYyjeOuit3wQ6uRTlsKQWitnmjxlVc6dR9l2+ogIjKIv9cFjhmrYvejVVCXkk38RFE4qVGVd/N+6L16HS/iVOxpZM9BXTFo6R0ImWrUhsG+zBhGZwSiF1YV6qp1wRlibDpBBDrSYSJ+YoMEmCrxAM=
